label scene11:
    scene bg_riley_quarters
    "Morning comes all too quickly."
    "I lift myself out of bed, wondering where Lily is."
    r "Lily?"
    l "Ahh~!"
    "A quick moan that I recognize as Lily's emanates from the bathroom."
    "I can only imagine what she's up to this morning..."
    "I do my best to peek inside."
    "Sure enough, Lily is occupied with stroking her member."
    "She's not even aware I'm watching her."
    l "Mmm...hnng..."
    "Her cock twitches and throbs, with her breath quickening with every stroke."
    "Eventually..."
    l "Ahhhh~!"
    "Her cum shoots out in ropy strands over the sink, leaving her breathless."
    r "Ah, I see you've been enjoying the facilities here."
    l "R-Riley!"
    l "You nearly gave me a heart attack there."
    l "When did you get up? Did I wake you?"
    r "Oh, I've been up for a while."
    r "Long enough to catch the show."
    "Even with her tan, her blushing cheeks are easy to spot."
    "Honestly, it's kind of cute that beneath her serious demeanor is another fellow pervert."
    l "S-Sorry."
    r "It's okay. You can make up for it with our visit to my place."
    l "Right! Let me fill out the rest of the paperwork for that."
    r "Not covered in semen, I hope."
    l "..."
    "A few minutes later, Lily emerges from the shower, while I've been busy eating breakfast."
    l "Okay, let me take care of the paperwork for our trip."
    l "This'll just be for the day, so we can do something else after we finish up at your apartment."
    l "Anything you want to do?"
    r "I'll think about it on the way there."
    l "Great."
    "She taps a few buttons on her tablet, finishing her application."
    "A moment later, a chime sounds off, signaling that her request was successful."
    l "Okay, we can head out in a bit."
    r "Awesome. That was pretty quick. Are those requests normally that fast?"
    l "Paperwork here in The Corporation is mostly automated nowadays, so things like this are almost never touched by another angel."
    l "It's helpful for time-sensitive info, or if you want something done quick."
    r "Nice. That saves us some time."
    "We get our clothes on and prepare to head outside for the first time in months."
    #transition
    show riley_apartment
    "It's strange, looking at it again after being away for so long."
    "What was once familiar feels a bit older."
    "The neighbors next to me have moved out, and the walls have recieved a new coat of paint."
    "Meanwhile, the interior of my apartment looks more or less the same."
    r "It's... clean."
    l "Well, that's the 'benefit' of working for us."
    l "Whenever a human like you is, uh, 'recruited', we do what we can to keep that human's life as intact as possible."
    l "We get you a cover story, an agent that keeps things clean and keeps you alive with social media and emails."
    r "Cover story? What's mine?"
    l "I think yours is simple; you're on a long vacation abroad in another country."
    l "You've been having fun in Japan, staying at a nice ryokan in Sapporo."
    r "Huh. Neat. I like that."
    "I never thought to ask Lily about how my 'life' outside The Corporation is being handled, if at all."
    "It's actually reassuring, in a way."
    jump scene12
