label scene13:
    "I take the pill offered by Lily and immediately chew it up before I decide otherwise."
    r "Okay, so what should I do now? Just wait?"
    l "It'll take a few minutes to kick in. You had something to eat before coming here, right?"
    r "Yup. We should be good to go."
    r "I don't mind having an audience if you want to watch."
    show cg_rileydick1
    "I lean back on Lily's desk and await my transformation."
    r "You know, it's kind of weird thinking about that I'll no longer be 100% physically female after this."
    l "How so?"
    r "Well, in all the futanari... literature I've read, women who become futanari tend to either enjoy their new dick, or feel awkward about it."
    l "Where do you reside?"
    r "Eh, I've never really considered myself 100% mentally female. More like 70/30. I think I'll enjoy having both sets."
    r "First is my clit... Ah!"
    show cg_rileydick2
    "As if on cue, my entire lower half throbs, and I can actually see my clit poking forward."
    r "W-Wow... That's amazing."
    l "It got so big! Incredible."
    l "Some of our subjects had quite a bit of initial growth."
    l "Are you feeling okay?"
    r "Y-Yeah. Just...surprised me, that's all."
    "I take a few deep breaths of air, feeling my clit throbbing with each breath I take."
    show cg_rileydick3
    l "It's slowly getting bigger now."
    r "I can feel that. Wow..."
    "It's no longer a clit. It's a small penis at this point."
    "I can feel a little bit of swelling down there, too. Are those..."
    r "Looks like I grew some balls."
    "They're small, but I assume they'll be getting bigger in a moment."
    l "You're growing a lot faster than I was..."
    l "You must really have wanted this."
    r "It's... a fantasy of mine."
    r "Ah!"
    show cg_rileydick4
    "My new penis erupts forward several inches."
    "Oh God, that's a cock. Thobbing and burning for release."
    r "Huff... phew..."
    r "Nnng!"
    show cg_rileydick5
    "Oh shit, it's thickening before my eyes."
    "Several veins erupt underneath the skin, filling and stretching out my cock."
    "I can feel my balls getting bigger and bigger, too."
    r "S-Sho good..."
    "I can hear myself clenching my teeth as my pleasure skyrockets."
    "There's no greater feeling than what I'm experiencing right now."
    "Every muscle in my body is vibrating with pleasure, as if my nervous system is trying to re-wire everything to accomodate my new genitalia."
    l "Incredible. That's some of the fastest growth I've seen."
    l "You're so... girthy now."
    r "Oooh, Lily..."
    "I see her, enraptured by my cock's prodigious growth."
    "I want her body."
    "I want to pin her down and fuck the daylights out of her."
    r "Haaa... haaa..."
    l "Riley, do you need anything? You're probably feeling quite... lustful right now, so let me -- ah!"
    "It doesn't take me long to catch her off guard and pin her to the floor."
    #spacer
    r "You want more? I've still got some steam to blow off."
    show lily nude futa smile
    l "I was actually gonna say the same thing, actually."
    r "Well, allow me to continue, then. Want to see me riding you?"
    l "Okay, sure."
jump scene14
