label scene10:
    "It doesn't take much longer for our volunteer pair to finish up with their 'test'."
    "We help them clean up and give them instrutions to return to the lab for more testing over the next few days."
    l "All right, I think we can call it for today."
    r "Whew, good."
    l "Tired?"
    l "We can do something fun to relax."
    r "Oh? What did you have in mind?"
    l "There's a nice seafood restaurant with a two-for-one deal today."
    r "You had me at 'seafood'. Let's go!"
    scene bg_arco_cafe
    "The arcology looks really nice in the evening, with an artifical sunset making the whole thing look like something out of a movie."
    "It's so realistic, one could almost forget we're underground."
    r "So what's this seafood place like? Fresh imports from the human market?"
    l "Yes, you're right. We typically buy from local markets for some of the in-demand food, like seafood."
    l "We're looking into adopting some aquaculture, so that might change soon."
    r "Fish is fish. What's on the menu today?"
    "We approach the place in question, a quaint place on the street corner with some outdoor options."
    l "I think this time they have crab and lobster available."
    r "So we're eating all of them, right?"
    "Lily gives me a confirmatory nod."
    l "That's the plan. Two-for-one seafood is an opportunity I refuse to miss."
    #timeskip
    r "Oh fuck, that was amazing."
    "I pat my belly affectionately as we walk back. I might still be pregnant, but I'll always have room for a good meal."
    l "Glad you enjoyed it. It's rare for that place to have such a good deal."
    r "If I had cash I'd find a way to pay you back, seriously."
    l "Oh, no worries. Think of it as payment for services rendered."
    r "Thanks again."
    l "Speaking of, I took you out to ask you a question."
    r "Shoot."
    l "You've done so much for us and The Corporation, despite all of the circumstances that led you here."
    l "That being said, would you be interested in working for me again?"
    "That's a good question. While on one hand, my 'employment' wasn't exactly voluntary..."
    "I kind of like it here. Lily's actually not that bad a person, and the experiments are a far cry from what I thought they would be."
    r "I think I would. Might take a break though."
    l "Oh? Why's that?"
    r "Well, I'm pretty homesick, for starters."
    r "Believe it or not, I do like my little apartment. All my books and games are there too."
    l "I... could arrange a home visit for a day, if you want to."
    r "Really? You'd do that?"
    l "Normally we don't allow for it, but I think I can pull a few strings."
    l "Let's go tomorrow, after our tests are done."
    r "Oh wow, thank you!"
    "I'm honestly a little surprised. Lily's being awfully generous today."
    "It's kinda nice."
    show bg_hallway
    "We finally arrive back at my quarters after talking at length about my apartment."
    l "All right, I'll see you tomorrow, Riley."
    r "Don't want to come in for a coffee? Or a quick dessert?"
    l "...Sure."
    show bg_riley_quarters
    "She steps into my place."
    r "You know, it's been a while since I've had a girl over."
    r "What do you think of my humble abode?"
    l "It's cozy, I'll give you that."
    r "These are just the budget places for employees, right?"
    r "I'm sure they're nothing compared to yours."
    r "Wait, speaking of... where do you live, Lily?"
    l "I have a nice place on the upper floors."
    l "I'd take you there, but security is really strict upstairs."
    l "Sorry."
    r "Ah, no worries. I figured it was something like that."
    r "Well, I've got all sorts of snacks here. Want anything?"
    l "I'll take that coffee, actually."
    "We both take our time chatting over small snacks and drinks late into the night."
    "It's nice getting to know Lily outside of research and science."
    l "Ahh... it's getting late."
    r "You going?"
    l "Yeah. It's a bit of a trip to get upstairs."
    r "Well..."
    "I feel a bit selfish, but I don't want her to go just yet."
    r "Why not stay the night here? That way you can skip the trip."
    l "Hmm..."
    "She thinks about it for a bit."
    l "I don't see the harm in it."
    r "Great!"
    "I'm kind of happy to be with someone else for a while longer."
    "Being on my own has its perks, but I've been a bit hungry for companionship lately."
    "It's nice not having to fall asleep alone, even if just for one night."
    #timeskip
    jump scene11
