label scene14:
    scene bg_riley_quarters
    "About an hour later, we finally come down from our sexual high."
    "Lily and I retreated to my apartment for post-sex ice cream."
    "It's something we always do after we spend the evening together, and it's kinda fun."
    "We just turn our minds off for the rest of the night."
    show riley_futa underwear smile at center_left
    show lily_futa underwear smile at center_right
    r "Honestly, your guys' version of romantic comedy is so weird."
    show lily_futa question
    l "Hm? How so?"
    r "Well, the lead is usually some dorky guy trying to win over the female lead."
    r "The woman spurns his affections at first, but then things change and they fall in love."
    r "But here, they're either both dorky or just... catty towards each other."
    r "And then it turns into full-on making out."
    r "Are all angels like that?"
    show lily_futa neutral
    l "Well, some can be very petty towards each other."
    l "I have a colleague that keeps trying to one-up me, for example."
    r "Sounds fun."
    "We have these silly, inane conversations all the time. A bunch of these every so often has really made this job bearable."
    "A Lily that doesn't talk about science is actually pretty nice."
    "But despite all of this..."
    "...It's all gotta end at some point."
    r "So uh, this is is probably the last night we do this sort of thing, isn't it?"
    l "I... suppose so. At least, for a while."
    l "I'm going to be busy with the new pills, and handling all of the changes for all of the interested angels."
    show lily_futa smile
    l "But I'm not opposed to sneaking out and paying you a visit."
    r "Well, you know where I live, so feel free to swing by when you're all done."
    l "Of course. We've become close, despite all that's happened."
    l "Friends should keep in touch."
    r "Yeah. I'd like that."
    r "Got a social media account I can follow you on?"
    l "Sure, I can pass those to you."
    "After that we just... relax."
    #timeskip
    scene bg_riley_quarters
    "Morning comes, and with it, my final few hours at The Corporation."
    show riley_futa underwear smallsmile
    r "Hey."
    show lily_futa underwear smallsmile
    l "Good morning, Riley."
    r "So this is it..."
    r "It feels kinda weird going home after everything I've been through."
    l "We both changed a lot, that's for sure."
    r "I'll say!"
    "Lily and I get dressed and get ready to head home."
    l "Ah, wait. Let's swing by my lab. I have something for you."
    scene bg_lily_lab
    r "So what is this thing you want to show me?"
    l "It's nothing big, but..."
    show lily dildo_hold
    l "I'd like for you to have one of these."
    "It's a new Immaculate Conception."
    l "It's a new model we developed after your tests with the previous version."
    r "Really? That doesn't break any rules?"
    l "I'm the Director; I can pull the strings for someone who's worked so hard for me."
    r "Just as long as I don't get pregnant again..."
    l "Don't worry, this one doesn't have a cytogel capsule."
    l "There's some new features that I think you'll enjoy."
    r "Wow, Lily, thanks!"
    r "This is the nicest dick I've ever recieved!"
    r "Well, except yours, of course."
    l "Glad to hear I haven't lost my touch."
    l "Well, that's all I had. You ready to head home, Riley?"
    "I take a long look at the lab, at the windows outside, and finally, at Lily."
    "My new friend, sex partner, and fulfiller of my greatest fantasies."
    "I knew that this would eventually have to end, but we'll be together again soon."
    r "Yeah, let's go."
    #transition
    scene bg_riley_apartment
    "Coming back to my apartment, Lily and I sign off on the remaining paperwork."
    l "Okay, so that's an NDA to not reveal the products we tested, a compensation plan for your work, and finally, a release form."
    l "Looks like that's it."
    r "I'm still really impressed that this is all so streamlined."
    r "I'm going to miss that."
    l "Well, if you want, we could catch you on some other charge in a few weeks..."
    l "Maybe I'd have to take you for an 'extended' contract?"
    r "Ha!"
    r "We don't have to do that anymore. We can be with each other whenever we have time."
    l "You're right, of course. I'll try my best to keep in contact so we can meet up in the future."
    r "I look forward to it."
    l "Well..."
    l "Lily leans in, pecking me on the cheek."
    l "..."
    l "Sorry, I do this with... close friends a lot."
    r "Don't apologize. I appreciated it."
    r "But with me..."
    "I lean in and give her a long, intimate kiss on the mouth."
    r "...I go all the way with people I've slept with."
    l "I'll... have to remember that next time we meet."
    r "Of course."
    l "Well, for now..."
    l "I'll see you later, Riley. You've been quite the test subject."
    r "Oh, I know."
    r "See ya!"
    hide lily
    "I close the door, finally alone in my own space at last."
    "Nine months of research has finally come to a close."
    "The compensation was excellent."
    show riley_futa nude_embarassed
    r "I can't believe this is me now..."
    "When I think about how much I've changed, it's almost too much to belive."
    "I grew several cup sizes, carried a fake pregnancy, and finally, grew a whole new pair of genitalia."
    "On top of that, I fucked an honest-to-goodness angel."
    "No way would anyone believe me."
    "But... does that matter?"
    "I'm a whole new person now, and I intend to show that off."
    "After all, the NDA didn't say I couldn't post pictures of myself."
    "I could just as easily claim that I was born this way."
    show riley_futa nude_smirk
    r "Wonder where I can show off this new dick..."
    hide riley
    "A new, exciting opportunity awaits."
    return
