label scene11:
    scene bg_riley_quarters
    "Morning comes all too quickly."
    "I lift myself out of bed, wondering where Lily is."
    r "Lily?"
    l "Ahh~!"
    "A quick moan that I recognize as Lily's emanates from the bathroom."
    "I can only imagine what she's up to this morning..."
    "I do my best to peek inside."
    "Sure enough, Lily is occupied with stroking her member."
    "She's not even aware I'm watching her."
    l "Mmm...hnng..."
    "Her cock twitches and throbs, with her breath quickening with every stroke."
    "Eventually..."
    l "Ahhhh~!"
    "Her cum shoots out in ropy strands over the sink, leaving her breathless."
    r "Ah, I see you've been enjoying the facilities here."
    l "R-Riley!"
    l "You nearly gave me a heart attack there."
    l "When did you get up? Did I wake you?"
    r "Oh, I've been up for a while."
    r "Long enough to catch the show."
    "Even with her tan, her blushing cheeks are easy to spot."
    "Honestly, it's kind of cute that beneath her serious demeanor is another fellow pervert."
    l "S-Sorry."
    r "It's okay. You can make up for it with our visit to my place."
    l "Right! Let me fill out the rest of the paperwork for that."
    r "Not covered in semen, I hope."
    l "..."
    "A few minutes later, Lily emerges from the shower, while I've been busy eating breakfast."
    l "Okay, let me take care of the paperwork for our trip."
    l "This'll just be for the day, so we can do something else after we finish up at your apartment."
    l "Anything you want to do?"
    r "I'll think about it on the way there."
    l "Great."
    "She taps a few buttons on her tablet, finishing her application."
    "A moment later, a chime sounds off, signaling that her request was successful."
    l "Okay, we can head out in a bit."
    r "Awesome. That was pretty quick. Are those requests normally that fast?"
    l "Paperwork here in The Corporation is mostly automated nowadays, so things like this are almost never touched by another angel."
    l "It's helpful for time-sensitive info, or if you want something done quick."
    r "Nice. That saves us some time."
    "We get our clothes on and prepare to head outside for the first time in months."
    #transition
    show riley_apartment
    "It's strange, looking at it again after being away for so long."
    "What was once familiar feels a bit older."
    "The neighbors next to me have moved out, and the walls have recieved a new coat of paint."
    "Meanwhile, the interior of my apartment looks more or less the same."
    r "It's... clean."
    l "Well, that's the 'benefit' of working for us."
    l "Whenever a human like you is, uh, 'recruited', we do what we can to keep that human's life as intact as possible."
    l "We get you a cover story, an agent that keeps things clean and keeps you alive with social media and emails."
    r "Cover story? What's mine?"
    l "I think yours is simple; you're on a long vacation abroad in another country."
    l "You've been having fun in Japan, staying at a nice ryokan in Sapporo."
    r "Huh. Neat. I like that."
    "I never thought to ask Lily about how my 'life' outside The Corporation is being handled, if at all."
    "It's actually reassuring, in a way."
    "The Corporation has spoiled me with its glimpse into the future in terms of how everything is handled."
    "Automated paperwork that doesn't require human intervention, body-altering pills, and really good dildos."
    l "So, what else did you have in mind today?"
    r "Lunch? There's a great public market not too far from here."
    r "And lately, I've been craving the barbeque brisket they sell."
    l "Lead the way!"
    #timeskip
    show public_market
    "The public market is busy today, with various local grocers selling a wide variety of goods."
    "It reminds me of The Corporation's market, though that one looks more polished and sterile."
    "This one feels a lot more alive and lived-in."
    "It's ultimately why I'm eager to go home after I'm all done."
    "The Corporation might be tempting with all of their shiny tech, but I'd be missing out on the rest of the world."
    l "Riley, is that the barbeque place?"
    "And of course, all the greasy, fatty food I could eat."
    r "Yeah! That's the place."
    "The all-too-familiar smell of spice rubs, grilling meat, and butter wafts its way over to my nostrils."
    r "Fuck, that smells amazing. I'm going to order; you want anything?"
    l "That pulled chicken sounds good."
    r "Good choice. I'm going all-in on that rib platter."
    r "God, I missed this."
    "It doesn't take long to get our food delivered."
    "Lily's modest chicken sandwich and collared greens pales in comparison to my huge plate of ribs, cornbread, steamed veggies, and coleslaw."
    "I normally don't eat this much, but I think I deserve to pig out on a special day like this."
    l "Oh wow, this is great. What kind of sauce do they use?"
    r "It's a secret recipe, allgedly."
    r "And it's fucking delicious."
    r "Here, you have to try a rib. Come on."
    "Lily pulls a rib off of my plate and takes a bite."
    l "It's so juicy!"
    l "And the seasoning is... perfect. I don't know what else to say."
    l "This is really, really good."
    r "You've never been here? Don't you head out on vacations?"
    l "No, this is my first time. I usually only see the city on the way to the airport."
    l "I really only eat out around Malibu, so I'm not familiar with the local fare here."
    r "Well, now you have an excuse to come visit little old me when I'm all done."
    l "I think I could sneak out every once in a while. Especially if the food here is this good."
    r "Great! It's a date."
    "The rest of the afternoon is spent window shopping and walking around one of the local parks."
    "It's a nice, pleasant afternoon."
    #timeskip
    show bg_riley_quarters
    "Finally, we return to The Corporation, with thoughts of good barbeque still in my mind... and in my stomach."
    r "I'm still full from lunch, wow."
    l "You ate quite a bit more than I did. I'm impressed that it all fit in there."
    r "I don't know how I did it, to be honest. Maybe my body just needed all of that today?"
    "Lily shrugs. Guess understanding of the digestive system isn't as advanced as, say, making my boobs bigger."
    r "Anyway, I think I'm gonna relax this evening. Want to join?"
    l "I suppose I could. There's not much left to do at the lab, anyway."
    "She sits down on the bed and motions to me to join her."
    "This'll be a nice evening, I think."
    #long timeskip
    jump scene12
