label scene8:
    #long timeskip
    scene bg_riley_quarters
    "It's been two months since I learned that Lily's experiments have been focusing on angelic pregnancies."
    "I've mainly been helping Lily with the paperwork and documentation involved in the pills and dildo she's created."
    "All while monitoring my own pregnancy."
    "Speaking of, today..."
    show cg_riley_preg4
    "I'm noticing that I've grown again."
    "My belly is enormous now; it's gotten to the point where it's further out than my boobs."
    "What's more, all of my organs have shifted around so I can't eat much, lest I get sick."
    "Thank God I didn't get morning sickness during all of this, either."
    "According to Lily, the cytogel releases a tiny amount of painkillers and dopamine to help with my growing body."
    "All the stuff you normally hear about pregnancy - the nausea, the mood swings, and even stuff like lactation - haven't happened."
    "I guess I could call myself lucky..."
    r "Ugh. Fuck."
    "I groan as I realize that I'm stuck this way for another 12 months."
    "Seriously, if I ever meet the angel who requested this design..."
    "..."
    "Whatever."
    "Before I can wallow in my own self-pity, I decide to heave my body over to the shower and get ready to head to the lab."
    #timeskip
    show riley bigpreg_hold_frown at centered
    r "Wow, I still can't believe how big this thing is."
    "Out of habit, I massage my pregnant belly as I walk around the small living space I've been given."
    show riley bigpreg_hold_neutral
    "It's oddly soothing."
    "Maybe it's the dopamine?"
    #timeskip
    show cg_riley_preg4_lab
    l "Wow, you've really grown."
    r "Ugh, not helping!"
    "Lily does her usual checkup on me."
    l "Would you like to know how much?"
    r "Not in particular, but I assume you want to tell me anyway?"
    l "Of course."
    l "This is pretty interesting. Your first few months you had some slow, but steady growth."
    l "But these last few hours you grew quite a lot!"
    l "The cytogel is fully mature; it's about 20 inches long now."
    r "Fun. Exciting."
    l "Didn't you say you wanted to be more invested in the baby?"
    r "Stop calling it that. It's not a baby!"
    l "Just teasing, Riley."
    r "What I said was that I'd be more interested in the science behind this."
    r "At the very least I'd like to see if you could make different strains of this stuff."
    r "Different gestation length, for starters."
    show bg_lily_lab
    show riley maternity_bigpreg_neutral
    show lily smile
    l "Well, that's it for this examination."
    l "Remember what I said during your last growth spurt?"
    show lily smile_pill
    l "Now that you've finished growing, now you can try this new pill I developed!"
    "Ah, crap. I knew there was a reason she was excited to see me today."
    "Well, I guess it can't be all that bad."
    r "All right, hit me. What crazy stuff will happen to me now?"
    l "That's up to you."
    l "This pill has a specific focus that affects your body."
    l "You don't even need to focus on anything this time."
    l "Don't worry, it's nothing extreme like adjusting your breast size."
    l "I was more interested in influencing some smaller changes."
    r "Like...?"
    l "Can't tell you, that --"
    r "Would impact the experiment. Gotcha."
    show riley maternity_bigpreg_shrug
    "I take the pill from her hand and start chewing."
    "Huh, this one tastes like chocolate."
    r "Why chocolate?"
    l "I just thought you might like something different."
    r "No complaints here."
    "I swallow the rest of the pill and wait."
    "..."
    r "Anything supposed to happen now?"
    l "Hmm... Give it a few more minutes."
    "I do as she says and dutifully wait there, wondering what, if any, changes are already occuring in my body."
    "My bets are on something related to my pregnancy."
    #timeskip
    l "..."
    l "Hm, I think this should have already taken effect..."
    l "Riley, how are you feeling?"
    r "More or less the same."
    l "Well then, I think we can call this one a dud. It might not have the right triggers to work at the current moment."
    r "That can happen?"
    "This is the first I've heard of one of Lily's things not working on the first try."
    l "I don't think it's anything we need to worry about."
    l "Come on, let's go get something nice to eat today."
    r "Only if you're buying."
    l "Don't I always buy?"
    r "...That's the joke."
    #transition
    scene bg_arco_food
    r "Why didn't you tell me you had one of these?"
    "I happily munch down on a thick, juicy hamburger."
    "God, it's been so long since I had something so fatty."
    l "Meat's hard to come by here. We mostly grow it in the lab, but it takes a long time."
    l "It's around this time of the year that a new crop of meat is released."
    r "That's so weird. Why do it this way?"
    l "It's better than importing foreign meats into the arcology, and we can control how much we produce."
    r "I'm impressed something this big came out of a petri dish."
    r "So no cows were harmed in the making of this burger?"
    l "Nope. Technically, it's vegan."
    r "Awesome."
    "I finish off the burger, picking out the scraps of lettuce between my teeth."
    r "Got another one of those?"
    "I blurt out a request before I realize that I'm still hungry for some reason."
    l "Uh, sure. Want something different?"
    r "Can you get cheese?"
    l "Sure."
    "Lily calls over a waitress, who comes back with another burger, just as juicy as the last."
    "My whole body feels amazing as I take another bite."
    "I'm so warm..."
    show lily surpise
    show riley maternity_bigpreg_milk_smile
    l "Riley! Your shirt!"
    r "What? Did I drip some ketchup on there or..."
    r "Oh geez, is this sweat or..."
    r "Uh..."
    show riley maternity_bigpreg_milk_surprise
    "As I grab my shirt, I feel it."
    "Something coming out of my breasts."
    r "I'm lactating?!?"
    l "So it does work! It must have needed some additional protein and fat to get going."
    l "Fascinating..."
    r "Now's not the time, Lily! Help me out here!"
    jump scene9
