label scene8:
    "Wiping off the sweat and remaining milk from a hot shower, I carefully put on my clothes and re-join Lily in the lab."
    show lily smile
    l "Perfect timing, Riley."
    show lily pill_red
    "She holds up a red-colored pill."
    l "I just finished up my next batch of pills."
    r "Cool, I'll take it."
    l "Actually..."
    "She hesitates a little bit."
    r "What?"
    l "I think for this one I'll need to test things on myself."
    l "It's meant for angels instead of humans."
    show riley maternity_bigpreg_smirk
    r "Really? You guys don't need to test this on other guinea pigs like myself?"
    l "Normally, yes. But I'm confident that this will work."
    l "Now hold on. I need to remove my pants."
    show cg_lily_pillscene1
    r "Woah!"
    "In one smooth motion, she's removed her pants and underwear, showing off her bare crotch."
    l "Riley, I'll need you to take notes and record this next part for me."
    l "These changes require a lot of my concentration."
    r "O-On it!"
    "I take her tablet and enable video recording."
    r "All set here. Go for it, Lily."
    l "Okay."
    show cg_lily_pill2
    "She swallows the pill without hesitation."
    l "Not bad."
    "Ten seconds pass."
    r "...Anything?"
    l "This might take some time. There's going to be a lot happening if this works."
    #timeskip
    "A few tense moments later..."
    l "Riley, I feel something. Focus the camera on my groin."
    r "Okay!"
    show cg_lily_pillzoom1
    "I zoom in on her, making sure things are in focus."
    "Her clit's gotten a lot bigger. Plumper."
    l "Okay, just describe what's happening to me in real time."
    r "Your clitoris is bigger."
    l "Great, that's step 1."
    l "The clitoris thickening and getting longer is first..."
    l "Ah!"
    show cg_lily_pillzoom2
    "As she says it, her clit twitches and jumps forward by what I swear is a solid inch."
    r "Oh shit, it uh, grew bigger again."
    r "There's a lot of lubrication forming, too."
    "Lily doesn't answer, only letting out a soft moan."
    "I resume narrating Lily's ever-changing genitalia."
    show cg_lily_pillzoom3
    r "At four minutes, thirty-seven seconds, subject's clitoris has grown another three inches."
    l "Hnng..."
    r "Subject is clearly aroused."
    show cg_lily_pillzoom4
    r "Clitoris now resembles a... penis."
    "I can't believe she did this to herself for her own research."
    r "Is that it, Lily?"
    l "T-there's m-more..."
    "Her breath is ragged, either from all of the changes taking place in her body, or from the sheer arousal."
    show cg_lily_pillzoom5
    r "Skin under the subject's new shaft is now growing."
    "Is that what I think it is?"
    show cg_lily_pillzoom6
    "Two lumps slip underneath the skin, confirming my hypothesis."
    r "Subject has developed testicles."
    "It's amazing. Lily's grown a real set of male genitalia, seemingly using her clit as a base for the new penis."
    "I didn't see any other changes, so her vagina and uterus must be intact for now."
    l "Ah! Ahh!"
    show cg_lily_pillzoom7
    "With everything completed, Lily's body twitches and convulses."
    "Her new cock gets rock hard, thobbing with heat and dripping precum."
    l "Hahh... hahh..."
    r "Lily? Everything okay?"
    show cg_lily_pillscene3
    "I take a good look at Lily's face, which has been contorted into an aroused, lewd face."
    l "It's so good! So... good!"
    show cg_lily_pillscene4
    "She's lost her cool, relaxed demeanor."
    "That new cock of hers looks ready to explode, too."
    l "Ugh... Riley... fuck..."
    "Before I can react, she grabs me and shoves me against her desk."
    "Geez, she's strong."
    "It isn't long before she takes off my clothes, too."
    r "Okay, okay! Get going before you make a mess."
    "This is how all of those hentai get started, right?"
    "Girl grows a dick, girl loses control, and finally..."
    show cg_riley_lily1
    "Girl fucks another girl."
    "Lily's thobbing cock feels extremly hot as she thrusts right in."
    "God, she's big."
    "Good thing I'm not dry down there."
    "I think the cytogel makes some extra lubrication for me, so I'm basically always wet nowadays."
    l "Riley! Riley!"
    "Lily can only say my name as she fucks me."
    "She's like that one dude I hooked up with in college."
    "He fumbled his way to an awkward orgasm, but damn if he didn't have the biggest dick I've ever seen."
    "Lily's... is bigger."
    "It's hitting all the right places, too."
    "Is this part of her angelic lineage?"
    "Her skin and her hair is flawless."
    "Even while she's balls deep in me, her body looks incredible."
    show cg_riley_lily2
    "She's clearly getting used to the motions of thrusting in and out now."
    l "So... good..."
    "How the hell has she not cum yet?"
    r "You doing okay?"
    l "Hahhh..."
    r "I'll... take that... as a yes."
    "This is starting to get really good on my end, too."
    "My clit's been rubbing against the smooth desk, so I'm getting really close."
    "Just... a little more..."
    l "R-Riley, I'm..."
    show cg_riley_lily3
    "She ejaculates inside of me."
    "No, that's not really a good descriptor."
    "It's more like she released a river of semen into me."
    "It gushes out endlessly, filling me up in less than a second."
    show cg_riley_lily4
    l "Hahhh... oh wow..."
    "She pops out, letting her accumulated semen slosh out of me."
    "For a few moments, all is silent as we both pant, trying to catch our breath."
    show cg_riley_lily5
    l "Wait!"
    "With incredible speed, she plucks a beaker from the top of the desk and holds it next to my vagina."
    l "There... we go."
    r "Really? At a time like this?"
    l "Need to... test if this is viable."
    "Oh yeah, that's the whole reason she grew a penis in the first place."
    "After a moment, she pulls the beaker away, full of her semen."
    r "You came a lot. Did you really like fucking me that much?"
    l "I... can't argue with the evidence here."
    r "Well, for your first time..."
    r "Not bad."
    l "Um, well. That will be all for today."
    #timeskip
    scene bg_riley_quarters
    "Whew, what a day."
    show riley_bigpreg_underwear_neutral
    "I certainly wasn't expecting getting fucked by a futanari today."
    show riley_bigpreg_underwear_smile
    "But hey, I can't even be mad at her."
    "This is so fucking cool!"
    "All of my perverted fantasies are becoming true, right before my eyes."
    "It's... incredible."
    "At the same time, this means that Lily is onto something big."
    "If that semen she colledted is actually viable, we've got to expand our testing to other angels."
    show riley_bigpreg_underwear_smirk
    "First angels, then breast expansion, pregnancy, lactation and finally, futanari."
    "I'm almost expecting some other freaky fetish to show up during my time here."
    "Who knows what tomorrow will bring?"
    jump scene9
