label scene7:
    scene bg_lily_lab
    "By the time we get back to the lab we're both in an interesting conversation about angel biology."
    r "So, angels were created after humans were?"
    l "Yes. Sometime after the first major population of Homo Sapiens was already on the planet, Our Progenitor made us based off of your genetic template."
    l "From what we understand we were meant to be a significant improvement over humans."
    l "However, humans have changed so radically over the past few millennia in terms of intellect that now that gap is significantly smaller."
    show riley maternity_medpreg_smile at center_left
    show lily smile at center_right
    l "Heh, well said."
    show riley maternity_medpreg_question
    r "So who exactly is this Progenitor? God?"
    l "If you're talking about the biblical God... kind of."
    l "Our records indicate that Our Progenitor started influencing things here on Earth about 250,000 years ago."
    l "Coincicdentally, that's just around the time modern humans emerged."
    r "Why Earth? Did this guy go to any other planets?"
    l "Mars and Venus, you mean? They were already at their current state when they arrived."
    l "Completely uninhabitable."
    l "It seems Earth was an ideal testing ground for Our Progenitor, with a wide variety of life, and one species that deserved attention."
    show riley maternity_medpreg_surprise
    r "Humans?"
    l "That's right. Your species has the uncanny ability to adapt to any living condition."
    l "Coupled with your high intelligence, you were poised to become the dominant species of the entire planet."
    l "However, Earth was not a kind home for you."
    show riley maternity_medpreg_neutral
    l "Droughts and other natural disasters were bottlenecking your species, and extinction was likely without intervention."
    l "So Our Progenitor decided to give things a little push in the right direction."
    r "Like what?"
    l "Well, a few dozen millenia later, humans were encouraged to move out of Africa and into other parts of the world."
    l "At the same time, angels were created from a few select humans as a means to assist."
    l "Eventually, humans had settled into their new homes and angels were done with our first major project."
    r "So what happened to you after that?"
    l "Our Progenitor gave us one final directive: nurture the planet."
    "Angels sure have a strange history."
    r "With such a vague directive, you'd think this Progenitor would given you guys more powers."
    r "And made your species fertile."
    l "That's the thing: we originally were able to have children of our own."
    l "Slowly, however, we started losing that ability."
    l "We're pretty sure that resetting our bodies every thousand or so years affected our ability to reproduce."
    l "We still retain our abilities, but we've struggled to find a way to reverse this trend."
    r "I don't suppose you could get this Progenitor to come back, could you?"
    l "We've tried contacting them. Unfortunately, we don't know where they went."
    l "For all we know, they're in some distant galaxy doing something similar with another alien species."
    r "So all of your work is going to manipluate what your creator built on? Doesn't that come with risks?"
    show lily neutral
    l "A lot. For one, it could degrade our DNA even further and cause us all sorts of problems."
    show riley maternity_medpreg_surprise
    "I blanch."
    r "Wait, then what about me?"
    l "Oh, don't worry. I've made sure that that particular scenario can't happen."
    show riley casual_medpreg_neutral
    r "Phew. Good."
    l "We have access to our genome so it's pretty easy to look at genes and figure out what needs to be modifed."
    l "Since the human genome is virtually identical, it was easy to test new medicaton on."
    r "So I guess you weren't kidding when you said you needed a human for this role."
    r "Since you can't determine if angels could even survive, you had to test on something equivalent."
    r "If things went wrong and angels started dying, then you'd have a dwindling supply of people keeping the planet together."
    "Lily nods."
    l "Hence why I picked you. You came to us at the perfect time."
    l "Thanks to you, what would have been at least 10 years of red tape was trimmed down to a few hours of paperwork."
    show riley maternity_medpreg_question
    r "You're welcome, I guess?"
    l "Speaking of, I'll have the next experiments ready after your next growth spurt. I'll keep monitoring you in the meantime."
    r "Well, anything else on the menu today?"
    l "Not in particular. You're not experiencing any more growth for a while, so we'll be taking it easy for the next few weeks."
    r "All right."
    l "With all of the data I have on you, I'll be developing a new pill for you to try."
    l "After your next growth spurt you'll be testing their effectiveness."
    show riley maternity_medpreg_neutral
    r "These better not make me grow a penis."
    l "Don't tell me you're still hung up on that?"
    l "I'm still a ways off on making a pill that can modify genitalia to that degree."
    l "I think at the most, you'd just be making your current genitalia much bigger."
    show riley maternity_medpreg_shrug
    r "My junk's plenty big, so I'll pass."
    l "Suit yourself. Well, see you tomorrow!"
    #timeskip
    scene bg_riley_quarters
    show riley maternity_medpreg_neutral
    "Bigger genitalia aside, it sounds like Lily has a reason for me to be here."
    "While at first I thought I'd just be testing drugs, the fact that Lily needs me in order to solve an issue her entire race has been struggling with is kind of interesting."
    show riley maternity_medpreg_belly_smile
    "If anything, it makes carrying this thing a bit more bearable."
    r "Jeez, everything looks smaller now."
    "Being pregnant for 15 months... Hopefully I don't get too much bigger."
    "Still..."
    #undress sequence
    show riley underwear_medpreg_belly_smile
    "I can't deny that I feel pretty sexy right now."
    "Maybe it's the feeling of relief that I'm able to help Lily and her people out instead of just being a guinea pig."
    "Regardless, I think I'll try to enjoy this pregnancy now."
    #long timeskip
    scene bg_riley_quarters
    "It's been two months since I learned that Lily's experiments have been focusing on angelic pregnancies."
    "I've mainly been helping Lily with the paperwork and documentation involved in the pills and dildo she's created."
    "All while monitoring my own pregnancy."
    "Speaking of, today..."
    show cg_riley_preg4
    "I'm noticing that I've grown again."
    "My belly is enormous now; it's gotten to the point where it's further out than my boobs."
    "What's more, all of my organs have shifted around so I can't eat much, lest I get sick."
    "Thank God I didn't get morning sickness during all of this, either."
    "According to Lily, the cytogel releases a tiny amount of painkillers and dopamine to help with my growing body."
    "All the stuff you normally hear about pregnancy - the nausea, the mood swings, and even stuff like lactation - haven't happened."
    "I guess I could call myself lucky..."
    r "Ugh. Fuck."
    "I groan as I realize that I'm stuck this way for another 12 months."
    "Seriously, if I ever meet the angel who requested this design..."
    "..."
    "Whatever."
    "Before I can wallow in my own self-pity, I decide to heave my body over to the shower and get ready to head to the lab."
    #timeskip
    show riley bigpreg_hold_frown at centered
    r "Wow, I still can't believe how big this thing is."
    "Out of habit, I massage my pregnant belly as I walk around the small living space I've been given."
    show riley bigpreg_hold_neutral
    "It's oddly soothing."
    "Maybe it's the dopamine?"
    #timeskip
    show cg_riley_preg4_lab
    l "Wow, you've really grown."
    r "Ugh, not helping!"
    "Lily does her usual checkup on me."
    l "Would you like to know how much?"
    r "Not in particular, but I assume you want to tell me anyway?"
    l "Of course."
    l "This is pretty interesting. Your first few months you had some slow, but steady growth."
    l "But these last few hours you grew quite a lot!"
    l "The cytogel is fully mature; it's about 20 inches long now."
    r "Fun. Exciting."
    l "Didn't you say you wanted to be more invested in the baby?"
    r "Stop calling it that. It's not a baby!"
    l "Just teasing, Riley."
    r "What I said was that I'd be more interested in the science behind this."
    r "At the very least I'd like to see if you could make different strains of this stuff."
    r "Different gestation length, for starters."
    show bg_lily_lab
    show riley maternity_bigpreg_neutral
    show lily smile
    l "Well, that's it for this examination."
    l "Remember what I said during your last growth spurt?"
    show lily smile_pill
    l "Now that you've finished growing, now you can try this new pill I developed!"
    "Ah, crap. I knew there was a reason she was excited to see me today."
    "Well, I guess it can't be all that bad."
    r "All right, hit me. What crazy stuff will happen to me now?"
    l "That's up to you."
    l "This pill has a specific focus that affects your body."
    l "You don't even need to focus on anything this time."
    l "Don't worry, it's nothing extreme like adjusting your breast size."
    l "I was more interested in influencing some smaller changes."
    r "Like...?"
    l "Can't tell you, that --"
    r "Would impact the experiment. Gotcha."
    show riley maternity_bigpreg_shrug
    "I take the pill from her hand and start chewing."
    "Huh, this one tastes like chocolate."
    r "Why chocolate?"
    l "I just thought you might like something different."
    r "No complaints here."
    "I swallow the rest of the pill and wait."
    "..."
    r "Anything supposed to happen now?"
    l "Hmm... Give it a few more minutes."
    "I do as she says and dutifully wait there, wondering what, if any, changes are already occuring in my body."
    "My bets are on something related to my pregnancy."
    #timeskip
    l "..."
    l "Hm, I think this should have already taken effect..."
    l "Riley, how are you feeling?"
    r "More or less the same."
    l "Well then, I think we can call this one a dud. It might not have the right triggers to work at the current moment."
    r "That can happen?"
    "This is the first I've heard of one of Lily's things not working on the first try."
    l "I don't think it's anything we need to worry about."
    l "Come on, let's go get something nice to eat today."
    r "Only if you're buying."
    l "Don't I always buy?"
    r "...That's the joke."
    #transition
    scene bg_arco_food
    show lily smile
    show riley maternity_bigpreg_smile
    r "Why didn't you tell me you had a burger joint?"
    "I happily munch down on a thick, juicy hamburger."
    "God, it's been so long since I had something so fatty."
    l "Meat's hard to come by here. We mostly grow it in the lab, but it takes a long time."
    l "It's around this time of the year that a new crop of meat is released."
    r "That's so weird. Why do it that way?"
    l "It's better than importing foreign meats into the arcology, and we can control how much we produce."
    r "I'm impressed something this big came out of a petri dish."
    r "So no cows were harmed in the making of this burger?"
    l "Nope. Technically, it's vegan."
    r "Awesome."
    "I finish off the burger, picking out scraps of lettuce between my teeth."
    "That was definitely one of the better burgers I've had."
    r "Got another one of those?"
    "I blurt out a request before I realize that I'm still hungry for some reason."
    l "Uh, sure. Want something different?"
    r "Can you get cheese?"
    l "Sure."
    "Lily calls over a waitress, who comes back with another burger, just as juicy as the last."
    "My whole body feels amazing as I take another bite."
    "I'm so warm..."
    "Even after becoming pregnant, I can't help but feel at peace right now."
    show lily surprise
    show riley maternity_bigpreg_milk_smile
    l "Riley! Your shirt!"
    r "What? Did I drip some ketchup on there or..."
    r "Oh geez, is this sweat or..."
    r "Uh..."
    show riley maternity_bigpreg_milk_surprise
    "As I grab my shirt, I feel it."
    "Something coming out of my breasts."
    r "I'm lactating?!?"
    l "So it does work! It must have needed some additional protein and fat to get going."
    l "Fascinating..."
    r "Now's not the time, Lily! Help me out here!"
    "Lily quickly tries to wipe me down, but it's no use."
    "My breasts are still leaking like a drippy faucet, so all we can do is stuff a few napkins under my shirt as we pay and rush out the door."
    "But... not before I wolf down the rest of the burger."
    #transition
    scene bg_lily_lab
    show riley maternity_bigpreg_milk_embarassed
    show lily neutral
    l "I can't believe that I missed that factor."
    l "It makes sense, though. Your body probably needed some extra calories in your system before any more changes could happen."
    r "So, what, I had to pig out to make it work? Why didn't I have to do that for when my breasts got bigger?"
    l "Well - and this is just a theory, mind - I think it had to wait for you to be mentally ready."
    l "Did you feel better after eating that burger, Riley? Like, really good?"
    r "...Yeah, kind of. I soft of recall feeling better about myself for some reason."
    l "Hmm, could have been from the pill you took. It 'primes' a change and just needs a mental trigger."
    l "If you thought about your pregnancy, coupled with the food you ate..."
    l "...it most likey kickstarted the lactation process."
    r "Well, the last time, I had something to eat before my breasts grew, so I guess I had the extra calories ready."
    r "And that video you made me watch certainly primed me for breast growth..."
    r "Wait, so what made me lactate this time?"
    l "If I'd have to guess, just thinking about your pregnancy in a positive light triggered the change."
    l "I'd have to make a few calibrations to the delivery system, but if positive thoughts shape the change, then that's easy to direct."
    r "I have no idea how you can make a tiny pill do all of that. I mean, 'positive thoughts' making my tits bigger?"
    r "You have to admit, that's a bit of a stretch."
    l "Well, it's all pretty simple, actually..."
    #timeskip
    "An hour later, Lily finally finishes her explaination of the science behind her pills."
    "Apparently nanomachines are involved?"
    "Most of it went over my head."
    l "Anyway, that's the gist of it."
    r "I guess if you program those nanomachines enough you can do pretty much anything, right?"
    l "Well, now that I have hard evidence, I can confidently say that, yes."
    l "Your participation led me to that conclusion!"
    "She seems pretty excited. I can't blame her - this is one of the biggest discoveries she's made."
    r "So uh... not to rain on your parade, but..."
    "I point to my wet shirt, still continuing to leak milk."
    r "When does this stop?"
    l "Hm, I suppose your milk production was accelerated due to the pill."
    l "Let me take care of that. Follow me."
    #transition
    scene bg_test_chamber_milk
    "Inside the test chamber this time is a pair of milking pumps dangling from the ceiling."
    "They look a lot like the industrial milkers attached to cows..."
    r "Hey, wait a minute. Just because I have these big things doesn't mean you have to treat me like one!"
    l "They're all we have on file. Angel's haven't needed to lactate for at least 12,000 years."
    r "Ah. I guess that makes sense."
    r "So this is all you have?"
    l "Don't worry, it's not going to go at full speed. I can control them with the tablet."
    r "All right."
    #undressing sequence
    show riley nude_bigpreg_milk_frown
    "My nipples have darkened a lot in just a few hours."
    "Well, I already have the belly, so I might as well accept the new nipples I've got."
    "Now it would be really hard to claim that I'm not pregnant."
    l "Ready?"
    show cg_milking_1
    "She guides me into the milking chair, where I can rest while still partially standing."
    l "Wait here, I'll attach the pumps to you."
    "As she sets up, my heartbeat begins to start increasing."
    "I'm... going to be milked."
    "Like some kind of animal."
    "I should be humiliated by all of this."
    "So why..."
    "...why am I getting so turned on?"
    "God, I'm such a pervert."
    show cg_milking_2
    with Dissolve
    l "Left pump is attached."
    show cg_milking_3
    with Dissolve
    l "Got the right pump ready."
    l "I'm going to start on the lowest speed, okay?"
    "I nod, too excited to say anything."
    l "If it hurts, you can tell me to stop."
    #milking sfx
    show cg_milking_4
    with Dissolve
    "The pumps immediately get to work, pulling at my sensitive nipples."
    "It feels like some pressure is being released as the milk starts flowing out."
    "I shudder in relief as the steady rhythm of the pumps work their magic."
    l "All good, Riley?"
    r "Hahhh... yeah..."
    "The primal, animalistic bent to this scene is only serving to increase my heartbeat more and more."
    "I'm shamelessly turned on by all of this."
    "To top it all off, Lily's watching my every move."
    "The mixture of embarassment and arousal feels way too good now."
    r "Mmm..."
    "A familiar heat between my legs indicates that I'm sopping wet."
    show cg_milking_5
    with Dissolve
    "Almost unconsciously, I start reaching down to masturbate, lost to the sensations."
    l "Riley! What are you doing?!?"
    r "H-huh?!?"
    "Lily snaps me out of my erotic display."
    l "Are you sure you're okay?"
    r "Y-yeah, I'm fine. This um... really feels good."
    l "...I see."

    jump scene8
