label scene9:
    #timeskip
    "The morning after sex is one of the best things in the world."
    "You bask in the memories of yesterday; the passion, the raw, sexual energy..."
    "And finally, the orgasm."
    show riley_bigpreg_underwear_smile
    "This is really something else."
    "I mean, a few months ago I'd think it would be crazy that angels existed, much less angels that can make some fantastic body-altering medicine."
    "Not that I'm complaining. After all, I've got some nice tits out of the deal."
    "The pregnancy was sort of a side effect of all of this, but at this point..."
    "...I guess I'm used to it."
    r "Wonder if Lily managed to find anything yet."
    scene bg_lily_lab
    "To no one's surprise, Lily is already hard at work."
    show lily neutral
    show riley maternity neutral
    "Even after drastic changes to her anatomy, she still manages to get to her lab early."
    show lily blush
    l "Oh, um, hello there, Riley."
    r "Hey."
    show lily neutral
    l "Sorry I uh, sent you home so abruptly after yesterday."
    r "It's cool. I figured that you'd want some time to yourself after, well, that."
    l "..."
    l "Yeah..."
    r "Any uh, side effects?"
    show lily blush
    l "..."
    l "I had..."
    l "..."
    r "Go on..."
    l "...an erection this morning."
    r "Oh, morning wood? Yeah that's pretty normal for guys."
    r "I guess now that you're a futanari it'll be a regular occurence."
    show lily question
    l "Futa...nari?"
    r "It's uh, a porn term for individuals with both genitalia."
    l "So, a hermaphrodite?"
    r "Technically that can cause offense to some people."
    r "So a lot of people online refer to people with both as futanari instead."
    l "Interesting."
    show lily happy
    l "Has a nice ring to it. I like it!"
    l "So, I'm a futanari now."
    show lily laugh
    l "Futanari. Futanari!"
    "She says it with several more inflections, trying it on like a new suit."
    r "Okay, enough. I get it. Congrats on your new status, Lily."
    r "Now, then, the other question: What about that semen you collected? Do you think it's viable?"
    show lily smile
    l "Oh yes! I actually was about to take a look at the sample before you came in."
    "She gestures to a microscope on her desk."
    l "Here goes..."
    "She leans down and adjusts the dials to bring the sample into focus."
    l "Hmmm..."
    l "Oh! They're moving!"
    r "Wait, what?!?"
    r "That means they're viable, right?"
    l "...Yes. I think so. Like, 90% certain about this."
    r "Does that mean you want to test on some other angels soon?"
    r "If it's viable, that is."
    l "I'll need to run a few more tests and then I can collect some volunteers."
    l "Riley, I'll need your help to filter some applicants. We'll need to establish some protocols for testing."
    r "Makes sense. I'm on it."
    "We spend the rest of the afteroon going over screening procedures, the effects of the futanari pills, and finally, sending emails to prospective angels."
    r "Phew. Done."
    r "You think we'll get anyone to try these out?"
    l "If there's enough angels interested in having children, then I think we'll get some eager applicants."
    r "Enough people with a pregnancy or impregnation fetish, you mean."
    l "What is it with you and fetishes?"
    r "Everyone has one. Trust me."
    r "I mean, I know for a fact that you love big boobs."
    r "Don't think that I didn't notice you groping my tits the other day."
    l "T-that was the..."
    r "Pills? Can't hide what you really want deep down inside."
    r "Hey, no one's gonna blame you for liking tits or ass or dicks or whatever."
    r "Just be true to yourself."
    l "..."
    l "I guess it wouldn't hurt to be more open."
    r "So, what are you, Lily? Tits or ass?"
    l "I like... bib brats."
    l "Big... brasts."
    r "Almost there."
    l "Big. Breasts!"
    r "There you go! You did it!"
    "I pat her on the back."
    l "I can't help but feel you're being facetious here..."
    r "Maybe a little. But you did tell me you like big breasts, right to my face."
    show riley_bigpreg_underwear_smirk
    r "Wanna touch 'em?"
    r "Come on, you've earned it. It's been a long day."
    l "..."
    "She gingerly reaches out for a grab."
    "Her hands are delicate, slowly pushing their way into my chest."
    l "These are... so soft!"
    r "Yeah. All natural, thanks to you."
    r "You know how much work like this costs outside? It's like, four grand."
    r "It's almost never real-looking, and you have to use implants to get the shape you want."
    r "Not to mention the months of recovery."
    r "But these pills? It cuts out that part in no time flat."
    r "And, well, you're clearly enjoying the results."
    l "You could say that."
    l "Well, I'm glad you like your new body, Riley."
    l "I sort of felt bad for decieving you when we first met, but it seems you've adapted well."
    r "Well, I mean, I'm annoyed that I wasn't really given a choice here, but what got me here in the first place was pretty much my fault."
    r "I poked around where I really shouldn't have and got punished for it."
    l "If we were an ordinary corporation you probably would have gotten away with it, actually."
    r "Seriously?"
    l "We caught you mainly because we had a team of specialists predict you would."
    r "What, like precognition?"
    l "Yes. There's a percentage of us with some psychic powers."
    r "Shit, really? Wait, are you psychic?"
    l "No, but I was blessed with an ability to precicely manipulate small molecules."
    r "You're pulling my leg."
    l "How else do you think I got those pills to work so effectively?"
    r "A good computer?"
    l "Well, that and my ability. Machines can only get so precise, so our angelic abilities help make our lives a lot easier."
    l "It's also why we've continued to be ahead of humans in terms of tech."
    r "Sounds like you got the better deal."
    l "The precog wing of The Corporation is pretty powerful, since they can predict so precicely."
    l "It's where most of our budget goes to, in any case."
    r "If I were a CEO I'd sure as hell want to make sure my army of psychics were well-paid."
    "We both share a laugh."
    l "Well anyway, I need to email some of the candidates. I have a married angel pair that can meet up with us tomorrow."
    l "Want to see them in action?"
    r "Ha. You really have to ask?"
    #timeskip
    show lily bg_lily_lab
    "The next day, as promised, the angel volunteers take their dose of respective magic pill, and let nature work its course."
    "We take them to an observation room and watch the show."
    r "That didn't take long. Did you see the look on her face when her dick popped out?"
    show lily smirk
    l "Indeed."
    r "So what's next?"
    show lily neutral
    l "Well, a pregnancy might not happen right away, so they'll have to come back here for more testing."
    l "Once we get a successful impregnation I'll run similar tests to what you've been undergoing during yours."
    r "But for now we just get to watch the peep show?"
    l "For 'research', of course."
    l "Not that my new subjects mind. I mean, look how happy they are."
    "Looking through the window, I can't deny that our pair of volunteers are very happy."
    "And hey, if this works, that means we'll have a lot of research completed."
    r "I'll keep my fingers crossed for you." 
    jump scene10
